# Generated by Django 5.2 on 2025-04-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.RenameField(
            model_name='student',
            old_name='join_date',
            new_name='enrollment_date',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
