# Generated by Django 5.2 on 2025-04-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_student_joining_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='joining_date',
        ),
    ]
