# Generated by Django 5.2 on 2025-04-04 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_remove_student_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
